version: "3.3"

services:
  sam-cli:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
    working_dir: /app
    environment:
      - AWS_DEFAULT_REGION
      - AWS_REGION
      - AWS_SESSION_EXPIRATION
      - AWS_SECRET_ACCESS_KEY
      - AWS_ACCESS_KEY_ID
      - AWS_ACCOUNT_ID